create table test.hospital
(
    addr           varchar(128) not null,
    yadmNm         varchar(64)  not null,
    clCd           varchar(4)   null,
    clCdNm         varchar(16)  null,
    cmdcGdrCnt     int          null,
    cmdcIntnCnt    int          null,
    cmdcResdntCnt  int          null,
    cmdcSdrCnt     int          null,
    detyGdrCnt     int          null,
    detyIntnCnt    int          null,
    detyResdntCnt  int          null,
    detySdrCnt     int          null,
    drTotCnt       int          null,
    emdongNm       varchar(16)  null,
    estbDd         varchar(8)   null,
    hospUrl        varchar(255) null,
    mdeptGdrCnt    int          null,
    mdeptIntnCnt   int          null,
    mdeptResdntCnt int          null,
    mdeptSdrCnt    int          null,
    pnursCnt       int          null,
    postNo         varchar(6)   null,
    sgguCd         varchar(8)   null,
    sgguCdNm       varchar(16)  null,
    sidoCd         varchar(8)   null,
    sidoCdNm       varchar(16)  null,
    telno          varchar(24)  null,
    XPos           float        null,
    YPos           float        null,
    ykiho          varchar(255) null,
    wrkTm          text         null,
    primary key (addr, yadmNm)
);

